;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Msg.Locomotiion.Trans.StartTo Cycle",NewTagName="Msg.Locomotiion.Trans.StartToCycle")
+GameplayTagRedirects=(OldTagName="State.ComboWindow.NormalWindow",NewTagName="State.ComboWindow.First")
+GameplayTagRedirects=(OldTagName="State.ComboWindow.TransToKSXLZ",NewTagName="State.ComboWindow.First")
+GameplayTagList=(Tag="Msg.Locomotiion.Trans.IdleToTurn",DevComment="")
+GameplayTagList=(Tag="Msg.Locomotiion.Trans.StartToCycle",DevComment="")
+GameplayTagList=(Tag="Msg.Locomotiion.Trans.TurnToCycle",DevComment="")
+GameplayTagList=(Tag="State.ComboWindow.First",DevComment="")
+GameplayTagList=(Tag="State.ComboWindow.Second",DevComment="")
+GameplayTagList=(Tag="State.Locomotion.Trans.StartToCycle",DevComment="")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword",DevComment="大剑动作数据根标签")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.OverheadSlash",DevComment="直斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.WideSlash",DevComment="横扫斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.WideSlash.FollowUp",DevComment="横扫斩（派生）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.RisingSlash",DevComment="上捞斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.RisingSlash.FollowUp",DevComment="上捞斩（派生）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.SideBlow",DevComment="横击")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.SideBlow.FollowUp",DevComment="横击（派生）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlash",DevComment="蓄力斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlash.Lv1",DevComment="蓄力斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlash.Lv2",DevComment="蓄力斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlash.Lv3",DevComment="蓄力斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongChargedSlash",DevComment="强蓄力斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongChargedSlash.Lv1",DevComment="强蓄力斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongChargedSlash.Lv2",DevComment="强蓄力斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongChargedSlash.Lv3",DevComment="强蓄力斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongWideSlash",DevComment="强横扫斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongWideSlash.Lv1",DevComment="强横扫斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongWideSlash.Lv2",DevComment="强横扫斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.StrongWideSlash.Lv3",DevComment="强横扫斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash",DevComment="真蓄力斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash.PreHit",DevComment="真蓄力斩前段")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash.PreHit.Lv1",DevComment="真蓄力斩前段（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash.PreHit.Lv2",DevComment="真蓄力斩前段（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash.PreHit.Lv3",DevComment="真蓄力斩前段（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash.Lv1",DevComment="真蓄力斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash.Lv2",DevComment="真蓄力斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlash.Lv3",DevComment="真蓄力斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.LeapingWideSlash",DevComment="飞身跃入横扫斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.LeapingWideSlash.Lv1",DevComment="飞身跃入横扫斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.LeapingWideSlash.Lv2",DevComment="飞身跃入横扫斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.LeapingWideSlash.Lv3",DevComment="飞身跃入横扫斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount",DevComment="骑乘蓄力斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount.PreHit",DevComment="骑乘蓄力斩前段")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount.PreHit.Lv1",DevComment="骑乘蓄力斩前段（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount.PreHit.Lv2",DevComment="骑乘蓄力斩前段（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount.PreHit.Lv3",DevComment="骑乘蓄力斩前段（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount.Lv1",DevComment="骑乘蓄力斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount.Lv2",DevComment="骑乘蓄力斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedSlashMount.Lv3",DevComment="骑乘蓄力斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedJumpingSlash",DevComment="蓄力跳跃斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedJumpingSlash.Lv1",DevComment="蓄力跳跃斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedJumpingSlash.Lv2",DevComment="蓄力跳跃斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedJumpingSlash.Lv3",DevComment="蓄力跳跃斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedRisingSlash",DevComment="蓄力上捞斩")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedRisingSlash.Lv1",DevComment="蓄力上捞斩（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedRisingSlash.Lv2",DevComment="蓄力上捞斩（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.ChargedRisingSlash.Lv3",DevComment="蓄力上捞斩（第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.PlungingThrust",DevComment="下坠突刺")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.PlungingThrust.MultiHit",DevComment="下坠突刺（多段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.PlungingThrust.MultiHit.Lv1",DevComment="下坠突刺（多段，第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.PlungingThrust.MultiHit.Lv2",DevComment="下坠突刺（多段，第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.PlungingThrust.MultiHit.Lv3",DevComment="下坠突刺（多段，第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.WeaponAttackClutchClaw",DevComment="武器攻击 / 飞翔爪")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.WeaponAttackClutchClaw.Hit1",DevComment="武器攻击 / 飞翔爪（第1段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.WeaponAttackClutchClaw.Hit2",DevComment="武器攻击 / 飞翔爪（第2段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.WeaponAttackClutchClaw.MultiHit",DevComment="武器攻击 / 飞翔爪（多段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.WeaponAttackClutchClaw.Finisher",DevComment="武器攻击 / 飞翔爪（终结）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlashPower",DevComment="真蓄力斩（强击）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlashPower.Lv1",DevComment="真蓄力斩（强击，第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlashPower.Lv2",DevComment="真蓄力斩（强击，第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.TrueChargedSlashPower.Lv3",DevComment="真蓄力斩（强击，第3阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.Kick",DevComment="踢击")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.Tackle",DevComment="肩撞")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.Tackle.Lv1",DevComment="肩撞（第1阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.Tackle.Lv2",DevComment="肩撞（第2阶段）")
+GameplayTagList=(Tag="Data.AttackSpec.GreatSword.Tackle.Lv3",DevComment="肩撞（第3阶段）")

